cds_migrator_kit/circulation/items/api.py
cds_migrator_kit/circulation/items/cli.py
cds_migrator_kit/config.py
cds_migrator_kit/records/cli.py
setup.py

Logging is broken, I need to understand why!
I can also add some tests eventually. (closes #17)

Migrate items

---

.gitignore
cds_migrator_kit/circulation/__init__.py
cds_migrator_kit/circulation/items/cli.py
cds_migrator_kit/circulation/users/__init__.py
cds_migrator_kit/circulation/users/api.py
cds_migrator_kit/circulation/users/cli.py
setup.py

users: migrate users

---

MANIFEST.in
cds_migrator_kit/ext.py
cds_migrator_kit/records/cli.py
cds_migrator_kit/records/log.py
cds_migrator_kit/records/records.py
cds_migrator_kit/records/views.py
tests/test_migration.py

logs: fix logging reports, fix tests

---

cds_migrator_kit/circulation/__init__.py
cds_migrator_kit/records/cli.py
cds_migrator_kit/records/log.py
setup.py

logs: fix failing script for KeyError exceptions

---

cds_migrator_kit/records/cli.py
cds_migrator_kit/records/log.py
cds_migrator_kit/records/templates/cds_migrator_kit_records/index.html
cds_migrator_kit/records/utils.py
setup.py

to be merged after ( #31 )
- Solves the problem with two serials stored in one record
- cleans duplicated
- matches spelling mistakes and prints similarities

Cleaning serials

---

cds_migrator_kit/records/cli.py
cds_migrator_kit/records/log.py
tests/test_migration.py

* changed error handling
travis failing because of cds-dojson PR not merged yet

cli: add handling the migration field

---

cds_migrator_kit/records/cli.py
cds_migrator_kit/records/templates/cds_migrator_kit_records/document.html
cds_migrator_kit/records/templates/cds_migrator_kit_records/multipart.html

* Don't render subfield if there is none
Closes #37 
Requires https://github.com/CERNDocumentServer/cds-dojson/pull/244

cli: fix issues with rectype document

---

.github/workflows/tests.yml
cds_migrator_kit/rdm/migration/load.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/xml_processing/dumper.py
cds_migrator_kit/rdm/migration/transform/xml_processing/errors.py
cds_migrator_kit/records/log.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/129

files: add record versioning

---

cds_migrator_kit/config.py
cds_migrator_kit/migration_config.py
cds_migrator_kit/rdm/migration/README.md
cds_migrator_kit/rdm/migration/cli.py
cds_migrator_kit/rdm/migration/handlers.py
cds_migrator_kit/rdm/migration/load.py
cds_migrator_kit/rdm/migration/load/__init__.py
cds_migrator_kit/rdm/migration/load/load.py
cds_migrator_kit/rdm/migration/runner.py
cds_migrator_kit/rdm/migration/streams.py
cds_migrator_kit/rdm/migration/streams.yaml
cds_migrator_kit/rdm/migration/transform/models/overdo.py
cds_migrator_kit/rdm/migration/transform/models/summer_student_report.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/xml_processing/contributors.py
cds_migrator_kit/rdm/migration/transform/xml_processing/dumper.py
cds_migrator_kit/rdm/migration/transform/xml_processing/errors.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/contributors.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/parsers.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/regex.py
cds_migrator_kit/rdm/migration/transform/xml_processing/rules/base.py
cds_migrator_kit/rdm/migration/transform/xml_processing/rules/summer_student_report.py
cds_migrator_kit/records/log.py
cds_migrator_kit/records/templates/cds_migrator_kit_records/records.html
cds_migrator_kit/records/utils.py
setup.cfg

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/128

SSPN metadata: add migration rules

---

.gitignore
cds_migrator_kit/rdm/migration/README.md
cds_migrator_kit/rdm/migration/cli.py
cds_migrator_kit/rdm/migration/load/load.py
cds_migrator_kit/rdm/migration/stats/__init__.py
cds_migrator_kit/rdm/migration/stats/config.py
cds_migrator_kit/rdm/migration/stats/event_generator.py
cds_migrator_kit/rdm/migration/stats/log.py
cds_migrator_kit/rdm/migration/stats/run.py
cds_migrator_kit/rdm/migration/stats/search.py
cds_migrator_kit/rdm/migration/streams.yaml
cds_migrator_kit/rdm/migration/transform/models/summer_student_report.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/users.py
cds_migrator_kit/rdm/migration/transform/xml_processing/errors.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/parsers.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/regex.py
cds_migrator_kit/records/log.py

closes https://github.com/CERNDocumentServer/cds-rdm/issues/145

stats migration

---

cds_migrator_kit/rdm/migration/README.md
cds_migrator_kit/rdm/migration/load/load.py
cds_migrator_kit/rdm/migration/runner.py
cds_migrator_kit/rdm/migration/streams.yaml
cds_migrator_kit/rdm/migration/transform/models/affiliations.py
cds_migrator_kit/rdm/migration/transform/models/summer_student_report.py
cds_migrator_kit/rdm/migration/transform/transform.py
scripts/dump_legacy_recids_to_redirect.py

closes https://github.com/CERNDocumentServer/cds-rdm/issues/212

load: skip legacy recids that are marked as duplicates

---

cds_migrator_kit/migration_config.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/xml_processing/rules/base.py

depends on https://github.com/CERNDocumentServer/cds-rdm/pull/269

Beams as vocab

---

cds_migrator_kit/rdm/migration/load/load.py
cds_migrator_kit/rdm/migration/transform/models/summer_student_report.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/users.py
cds_migrator_kit/rdm/migration/transform/xml_processing/dumper.py
cds_migrator_kit/rdm/migration/transform/xml_processing/rules/affiliations.py
cds_migrator_kit/rdm/migration/transform/xml_processing/rules/base.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/265

users: check for existing person_ids

---

cds_migrator_kit/migration_config.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/contributors.py
cds_migrator_kit/rdm/migration/transform/xml_processing/rules/base.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/233

Names vocab

---

cds_migrator_kit/migration_config.py
cds_migrator_kit/rdm/migration/transform/transform.py
cds_migrator_kit/rdm/migration/transform/users.py
cds_migrator_kit/rdm/migration/transform/xml_processing/quality/contributors.py
tests/cds-rdm/conftest.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/281

Internal id integration

---

cds_migrator_kit/migration_config.py
cds_migrator_kit/videos/__init__.py
cds_migrator_kit/videos/weblecture_migration/__init__.py
cds_migrator_kit/videos/weblecture_migration/cli.py
cds_migrator_kit/videos/weblecture_migration/load/__init__.py
cds_migrator_kit/videos/weblecture_migration/load/load.py
cds_migrator_kit/videos/weblecture_migration/streams.py
cds_migrator_kit/videos/weblecture_migration/streams.yaml
cds_migrator_kit/videos/weblecture_migration/transform/__init__.py
cds_migrator_kit/videos/weblecture_migration/transform/models/__init__.py
cds_migrator_kit/videos/weblecture_migration/transform/models/base.py
cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/__init__.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/quality/__init__.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/quality/contributors.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/__init__.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/base.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
setup.cfg

closes https://github.com/CERNDocumentServer/cds-videos/issues/1999
- Streams config for workflow
- cli command for `invenio videos weblectures run`
- VideoLecture model for transform/rules
- Basic transform rules

videos: weblecture-migration setup

---

cds_migrator_kit/rdm/migration/README.md
cds_migrator_kit/rdm/migration/load/load.py

* closes: https://github.com/CERNDocumentServer/cds-rdm/issues/342

load: add default community

---

README.rst
cds_migrator_kit/videos/migration_config.py
cds_migrator_kit/videos/weblecture_migration/load/helpers.py
cds_migrator_kit/videos/weblecture_migration/load/load.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/transform_files.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/quality/contributors.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
tests/cds-videos/test_videos_transform_rules.py

Load is still in progress. 
closes https://github.com/CERNDocumentServer/cds-videos/issues/2001
- Better approach for validating the dates
- Implemented create-publish record mechanism with **files**
- Copy the master video file to correct FileInstance folder
- Upload frames and subformats without running the celery task
- Upload additional files
Tests will be implemented for the load

videos: basic loading mechanism

---

cds_migrator_kit/videos/weblecture_migration/load/load.py

https://github.com/CERNDocumentServer/cds-videos/issues/2004

videos: save the original dumped record

---

cds_migrator_kit/reports/log.py
cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/base.py
cds_migrator_kit/videos/weblecture_migration/users/transform/xml_processing/models/submitter.py
setup.cfg
tests/cds-videos/test_videos_transform_rules.py
tests/helpers.py

closes https://github.com/CERNDocumentServer/cds-videos/issues/2002?issue=CERNDocumentServer%7Ccds-videos%7C2017
closes https://github.com/CERNDocumentServer/cds-videos/issues/2002?issue=CERNDocumentServer%7Ccds-videos%7C2018

videos: add new transform rules and fix submitter model

---

cds_migrator_kit/rdm/migration_config.py
cds_migrator_kit/rdm/records/load/load.py
cds_migrator_kit/rdm/records/transform/config.py
cds_migrator_kit/rdm/records/transform/models/thesis.py
cds_migrator_kit/rdm/records/transform/transform.py
cds_migrator_kit/rdm/records/transform/xml_processing/rules/base.py
cds_migrator_kit/rdm/records/transform/xml_processing/rules/summer_student_report.py
cds_migrator_kit/rdm/records/transform/xml_processing/rules/thesis.py
cds_migrator_kit/reports/views.py
cds_migrator_kit/transform/xml_processing/rules/base.py
cds_migrator_kit/videos/weblecture_migration/cli.py
cds_migrator_kit/videos/weblecture_migration/load/helpers.py
cds_migrator_kit/videos/weblecture_migration/load/load.py
cds_migrator_kit/videos/weblecture_migration/logger.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/transform_files.py

* related works: handle DOIS with qualifiers
* related works: add related records
* related works: add related conferences records via recid
* add related publications via recid
* dates: improve dates
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/381
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/354
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/380

copyrights: map copyright field

---

cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
tests/cds-videos/test_videos_transform_rules.py

closes https://github.com/CERNDocumentServer/cds-videos/issues/2020

videos: rename internal_note to note and add to metadata

---

cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
tests/cds-videos/test_videos_transform_rules.py

closes https://github.com/CERNDocumentServer/cds-videos/issues/2019

videos: add rule for location

---

cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
tests/cds-videos/test_videos_transform_rules.py

Only last commit for review :)
closes https://github.com/CERNDocumentServer/cds-videos/issues/2026

add transformation rule for document-contact

---

cds_migrator_kit/videos/weblecture_migration/load/helpers.py
cds_migrator_kit/videos/weblecture_migration/load/load.py
cds_migrator_kit/videos/weblecture_migration/logger.py
cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/transform_files.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/users/transform/xml_processing/models/submitter.py

Only last commit for review :)

Reformat code

---

cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/quality/contributors.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
tests/cds-videos/test_videos_transform_rules.py

closes https://github.com/CERNDocumentServer/cds-videos/issues/2030

videos: transform collaborators

---

.gitignore
cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/transform.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
tests/cds-videos/test_videos_transform_rules.py

closes https://github.com/CERNDocumentServer/cds-videos/issues/2033
closes https://github.com/CERNDocumentServer/cds-videos/issues/2034

transform subject_category and corporate_author

---

cds_migrator_kit/videos/README.md
cds_migrator_kit/videos/weblecture_migration/cli.py
cds_migrator_kit/videos/weblecture_migration/load/helpers.py
cds_migrator_kit/videos/weblecture_migration/load/load.py
cds_migrator_kit/videos/weblecture_migration/streams.py
cds_migrator_kit/videos/weblecture_migration/streams.yaml
cds_migrator_kit/videos/weblecture_migration/transform/folders_transform.py
cds_migrator_kit/videos/weblecture_migration/transform/models/base.py
cds_migrator_kit/videos/weblecture_migration/transform/models/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/base.py
cds_migrator_kit/videos/weblecture_migration/transform/xml_processing/rules/video_lecture.py
cds_migrator_kit/videos/weblecture_migration/users/runner.py
cds_migrator_kit/videos/weblecture_migration/users/transform/xml_processing/models/submitter.py

closes https://github.com/CERNDocumentServer/cds-videos/issues/2113

videos: recipe and command for copying ceph files
